import type { GmailMessage } from './types'

// デモGmailデータ — 実際のGmailアカウントから取得したものではない
export const mockGmailMessages: GmailMessage[] = [
  {
    id: 'gmail-mock-001',
    threadId: 'thread-001',
    subject: '【至急】融資審査に係る追加書類の提出について',
    from: '○○銀行 法人営業部 山田',
    fromEmail: 'yamada@xxx-bank.co.jp',
    date: new Date('2026-06-27T08:15:00'),
    snippet: '平素よりお世話になっております。融資審査に際し、追加書類の提出をお願いしております。',
    body: '平素よりお世話になっております。○○銀行 法人営業部の山田でございます。\n\n現在進行中の融資審査に際し、下記の追加書類のご提出をお願い申し上げます。\n\n■提出書類\n・直近3ヶ月の試算表\n・売掛金一覧表\n・主要取引先一覧\n\n大変お手数ですが、本日中にご提出いただけますと幸いです。\n\nご不明な点はお気軽にご連絡ください。\nよろしくお願いいたします。',
    hasAttachment: false,
    isUnread: true,
    labels: ['INBOX', 'IMPORTANT'],
    writeProtected: true,
  },
  {
    id: 'gmail-mock-002',
    threadId: 'thread-002',
    subject: '工事代金の未払いについてご連絡',
    from: 'A社 経理部 鈴木',
    fromEmail: 'suzuki@a-company.co.jp',
    date: new Date('2026-06-27T09:30:00'),
    snippet: '先月完了した解体工事の代金について、まだお振込みが確認できておりません。',
    body: 'お世話になっております。A社 経理部の鈴木です。\n\n先月完了した解体工事（工事番号：LCC-2026-045）の代金¥2,850,000について、\n本日現在、弊社銀行口座へのご入金が確認できておりません。\n\nご確認のうえ、今週中にお振込みいただけますと幸いです。\n\nご不明な点がございましたらご連絡ください。',
    hasAttachment: true,
    isUnread: true,
    labels: ['INBOX'],
    writeProtected: true,
  },
  {
    id: 'gmail-mock-003',
    threadId: 'thread-003',
    subject: '労働安全衛生法に基づく書類提出のお願い',
    from: '○○労働基準監督署',
    fromEmail: 'info@roudou-kansi.go.jp',
    date: new Date('2026-06-26T14:00:00'),
    snippet: '標記について、下記書類の提出期限が7月10日となっております。',
    body: '株式会社LCC 代表取締役 坂本様\n\n○○労働基準監督署です。\n\n標記について、下記書類の提出期限が7月10日（金）となっております。\n\n■提出書類\n・定期健康診断結果報告書\n・有機溶剤等健康診断結果報告書\n\n期限内にご提出いただきますようお願いいたします。',
    hasAttachment: false,
    isUnread: false,
    labels: ['INBOX'],
    writeProtected: true,
  },
  {
    id: 'gmail-mock-004',
    threadId: 'thread-004',
    subject: '契約書内容のご確認のお願い',
    from: 'B社 担当 田中',
    fromEmail: 'tanaka@b-company.co.jp',
    date: new Date('2026-06-27T10:00:00'),
    snippet: '先日お送りした契約書の内容をご確認いただき、ご署名・ご捺印をお願いしております。',
    body: 'お世話になっております。B社の田中です。\n\n先日お送りした設備工事請負契約書についてご確認をお願いしております。\n\n内容に問題がなければ、今週中に署名・捺印のうえご返送いただけますでしょうか。\n\nご質問がございましたらお気軽にご連絡ください。\nよろしくお願いいたします。',
    hasAttachment: true,
    isUnread: true,
    labels: ['INBOX'],
    writeProtected: true,
  },
  {
    id: 'gmail-mock-005',
    threadId: 'thread-005',
    subject: 'B現場 追加外注費の承認依頼',
    from: '加藤監督',
    fromEmail: 'kato@lcc55.com',
    date: new Date('2026-06-27T07:45:00'),
    snippet: 'B現場で追加外注が必要になりました。今日中に決定が必要です。',
    body: '社長、お疲れ様です。加藤です。\n\nB現場ですが、地中埋設物が想定外に多く発見され、\n追加外注費として¥480,000が必要な見込みです。\n\n今日中に外注先に連絡しないと明日の工程が止まってしまいます。\n\nご承認いただけますでしょうか。\nよろしくお願いいたします。',
    hasAttachment: false,
    isUnread: true,
    labels: ['INBOX'],
    writeProtected: true,
  },
]
