import type { GoogleDriveFile } from './types'

const today = new Date('2026-06-27T09:20:00+09:00').toISOString()
const yesterday = new Date('2026-06-26T17:30:00+09:00').toISOString()
const lastWeek = new Date('2026-06-20T10:00:00+09:00').toISOString()

const defaultOwners = [{ displayName: '山田太郎', emailAddress: 'yamada@example.com' }]

export const mockDriveFiles: GoogleDriveFile[] = [
  {
    id: 'file-001',
    name: '銀行提出資料_追加依頼_東京信金.xlsx',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    webViewLink: 'https://drive.google.com/file/d/file-001/view',
    createdTime: lastWeek,
    modifiedTime: today,
    owners: defaultOwners,
    parents: ['folder-bank'],
    size: '102400',
    starred: true,
    trashed: false,
    shared: false,
  },
  {
    id: 'file-002',
    name: '工事契約書_〇〇邸_2026年06月.pdf',
    mimeType: 'application/pdf',
    webViewLink: 'https://drive.google.com/file/d/file-002/view',
    createdTime: lastWeek,
    modifiedTime: yesterday,
    owners: defaultOwners,
    parents: ['folder-contract'],
    size: '102400',
    starred: false,
    trashed: false,
    shared: false,
  },
  {
    id: 'file-003',
    name: '未請求一覧_6月_お結び.xlsx',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    webViewLink: 'https://drive.google.com/file/d/file-003/view',
    createdTime: lastWeek,
    modifiedTime: yesterday,
    owners: defaultOwners,
    parents: ['folder-invoice'],
    size: '102400',
    starred: false,
    trashed: false,
    shared: false,
  },
  {
    id: 'file-004',
    name: 'お結び監査対応資料_TKC_2026上期.pdf',
    mimeType: 'application/pdf',
    webViewLink: 'https://drive.google.com/file/d/file-004/view',
    createdTime: lastWeek,
    modifiedTime: lastWeek,
    owners: defaultOwners,
    parents: ['folder-audit'],
    size: '102400',
    starred: true,
    trashed: false,
    shared: false,
  },
  {
    id: 'file-005',
    name: '車両事故報告書_〇〇車_2026-06-20.pdf',
    mimeType: 'application/pdf',
    webViewLink: 'https://drive.google.com/file/d/file-005/view',
    createdTime: lastWeek,
    modifiedTime: new Date('2026-06-21T09:00:00+09:00').toISOString(),
    owners: defaultOwners,
    parents: ['folder-accident'],
    size: '102400',
    starred: false,
    trashed: false,
    shared: false,
  },
  {
    id: 'file-006',
    name: '資金繰り表_2026年06月.xlsx',
    mimeType: 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    webViewLink: 'https://drive.google.com/file/d/file-006/view',
    createdTime: lastWeek,
    modifiedTime: yesterday,
    owners: defaultOwners,
    parents: ['folder-finance'],
    size: '102400',
    starred: true,
    trashed: false,
    shared: false,
  },
  {
    id: 'file-007',
    name: '見積書_〇〇社_2026-06.pdf',
    mimeType: 'application/pdf',
    webViewLink: 'https://drive.google.com/file/d/file-007/view',
    createdTime: lastWeek,
    modifiedTime: yesterday,
    owners: defaultOwners,
    parents: ['folder-estimate'],
    size: '102400',
    starred: false,
    trashed: false,
    shared: false,
  },
]
