// LINE WORKS モックデータ（Phase 9）
// 実際のLINE WORKS APIは未接続。全件デモデータ。
// 書き込み・送信・既読化は一切行わない。

import type { LineWorksNotificationMessage, LineWorksInboxMessage } from './types'

// ─── Notification Provider 用（緊急通知・事故・SOS系 5件）────────

export const mockLineWorksNotifications: LineWorksNotificationMessage[] = [
  {
    messageId: 'lw-notif-001',
    channelId: 'ch-field-001',
    channelName: '現場連絡グループ',
    senderId: 'user-tanaka',
    senderName: '田中 一郎',
    senderDepartment: '第1現場チーム',
    content: '本日11時30分頃、○○マンション現場にて作業車両と接触事故が発生しました。作業員1名が軽傷を負い、現在救急対応中です。警察への届出は完了しています。報告書を本日中に提出します。',
    sentAt: '2026-06-27T11:35:00+09:00',
    category: 'accident',
    urgency: 'critical',
    hasAttachment: false,
    isRead: false,
    readOnly: true,
    writeEnabled: false,
    riskFlag: true,
    importance: 'A',
    suggestedAction: '事故報告書の確認と保険会社への連絡。現場状況の把握後、速やかに対応を判断してください。',
    relatedLocation: '○○マンション現場（東京都渋谷区）',
  },
  {
    messageId: 'lw-notif-002',
    channelId: 'ch-hr-001',
    channelName: '総務・人事連絡',
    senderId: 'user-yamamoto',
    senderName: '山本 花子',
    senderDepartment: '福祉事業部',
    content: '【緊急】体調不良で出勤できません。39.2度の発熱があり、本日は休暇を取得します。担当している○○様の訪問介護（13:00〜）のフォローをお願いします。引き継ぎ内容を別途送ります。',
    sentAt: '2026-06-27T07:42:00+09:00',
    category: 'absence',
    urgency: 'high',
    hasAttachment: false,
    isRead: false,
    readOnly: true,
    writeEnabled: false,
    riskFlag: false,
    importance: 'A',
    suggestedAction: '午後13時の訪問介護の代替スタッフ確保が必要です。',
    relatedLocation: null,
  },
  {
    messageId: 'lw-notif-003',
    channelId: 'ch-field-001',
    channelName: '現場連絡グループ',
    senderId: 'user-suzuki',
    senderName: '鈴木 健太',
    senderDepartment: '第2現場チーム',
    content: '△△ビル改修工事の現場です。搬入資材の配送が2時間遅延しています。午前中の工程が遅れており、午後の作業も影響が出る見込みです。依頼先の運送会社に確認中です。',
    sentAt: '2026-06-27T09:15:00+09:00',
    category: 'delay',
    urgency: 'high',
    hasAttachment: false,
    isRead: false,
    readOnly: true,
    writeEnabled: false,
    riskFlag: false,
    importance: 'B',
    suggestedAction: '工程遅延の発注先への連絡と、納期調整が必要か確認してください。',
    relatedLocation: '△△ビル改修工事現場（東京都新宿区）',
  },
  {
    messageId: 'lw-notif-004',
    channelId: 'ch-field-001',
    channelName: '現場連絡グループ',
    senderId: 'user-ito',
    senderName: '伊藤 誠',
    senderDepartment: '第1現場チーム',
    content: '業務用バン（品川○○-○○）のエンジン警告ランプが点灯し、エンジンがかかりにくい状態です。現在○○SA駐車場にて停車中。ロードサービスに連絡しましたが、到着まで1時間程かかると言われています。現場への到着が遅れます。',
    sentAt: '2026-06-27T08:05:00+09:00',
    category: 'vehicle',
    urgency: 'high',
    hasAttachment: false,
    isRead: false,
    readOnly: true,
    writeEnabled: false,
    riskFlag: true,
    importance: 'A',
    suggestedAction: '代替交通手段の確保と現場への連絡が必要です。車両修理費用の確認も行ってください。',
    relatedLocation: '○○SA駐車場（東名高速）',
  },
  {
    messageId: 'lw-notif-005',
    channelId: 'ch-direct-001',
    channelName: 'ダイレクトメッセージ',
    senderId: 'user-sato',
    senderName: '佐藤 美咲',
    senderDepartment: '第3訪問チーム',
    content: '【SOS】訪問先の□□様が意識がもうろうとしており、呼びかけにも反応が薄い状態です。現在、救急車を呼んでいます。ご家族にも連絡しましたが、つながらない状態です。どうすればいいですか？',
    sentAt: '2026-06-27T10:52:00+09:00',
    category: 'sos',
    urgency: 'critical',
    hasAttachment: false,
    isRead: false,
    readOnly: true,
    writeEnabled: false,
    riskFlag: true,
    importance: 'A',
    suggestedAction: '救急対応中。ご家族への連絡継続と、担当ケアマネへの報告が必要です。事後の記録を確実に残してください。',
    relatedLocation: null,
  },
]

// ─── Inbox Provider 用（社内連絡・確認依頼系 4件）────────────────

export const mockLineWorksInboxMessages: LineWorksInboxMessage[] = [
  {
    messageId: 'lw-inbox-001',
    channelId: 'ch-sales-001',
    channelName: '営業・受注連絡',
    senderId: 'user-nakamura',
    senderName: '中村 大輔',
    senderDepartment: '営業部',
    content: '○○建設様から△△工事の見積書について確認依頼が来ています。先日提出した見積額に変更はないか、また工期の再確認をお願いしたいとのことです。今週中に返答が必要です。',
    sentAt: '2026-06-27T09:30:00+09:00',
    category: 'finance',
    urgency: 'high',
    hasAttachment: false,
    isRead: false,
    readOnly: true,
    writeEnabled: false,
    requiresApproval: true,
    priority: 'A',
    subject: '見積確認依頼：○○建設・△△工事',
    bodyPreview: '○○建設様から△△工事の見積書について確認依頼が来ています。今週中に返答が必要です。',
    deadline: '2026-06-30',
    suggestedAction: '見積書の最終確認と○○建設様への回答',
  },
  {
    messageId: 'lw-inbox-002',
    channelId: 'ch-finance-001',
    channelName: '経理・請求連絡',
    senderId: 'user-kobayashi',
    senderName: '小林 恵子',
    senderDepartment: '経理部',
    content: '□□介護サービス様への5月分請求書（¥480,000）について、6月末が支払期限ですが先方から振り込み遅延の連絡がありました。確認と督促の対応をお願いします。',
    sentAt: '2026-06-27T08:55:00+09:00',
    category: 'finance',
    urgency: 'high',
    hasAttachment: false,
    isRead: false,
    readOnly: true,
    writeEnabled: false,
    requiresApproval: true,
    priority: 'A',
    subject: '請求確認：□□介護サービス様5月分未入金',
    bodyPreview: '□□介護サービス様への5月分請求書（¥480,000）の支払期限が6月末です。振り込み遅延の連絡があり、対応が必要です。',
    deadline: '2026-06-30',
    suggestedAction: '□□介護サービス様への督促連絡と入金確認',
  },
  {
    messageId: 'lw-inbox-003',
    channelId: 'ch-hr-001',
    channelName: '総務・人事連絡',
    senderId: 'user-watanabe',
    senderName: '渡辺 陽子',
    senderDepartment: 'お結び事業部',
    content: 'お結び店舗（渋谷店）の来月シフトについて相談があります。パート2名が7月に育休を取る予定で、人手が不足します。求人を出すか、他店から応援をもらうか、社長のご判断をいただきたいです。',
    sentAt: '2026-06-27T10:10:00+09:00',
    category: 'operation',
    urgency: 'medium',
    hasAttachment: false,
    isRead: false,
    readOnly: true,
    writeEnabled: false,
    requiresApproval: false,
    priority: 'B',
    subject: 'お結び渋谷店：7月シフト人員不足の相談',
    bodyPreview: '来月、パート2名が育休予定で人手不足になります。求人か応援か判断をお願いします。',
    deadline: '2026-07-05',
    suggestedAction: '人員補充方針の決定（求人 or 応援）',
  },
  {
    messageId: 'lw-inbox-004',
    channelId: 'ch-finance-001',
    channelName: '経理・請求連絡',
    senderId: 'user-kobayashi',
    senderName: '小林 恵子',
    senderDepartment: '経理部',
    content: '△△銀行の融資審査に必要な決算書および試算表を提出する期限が来週7月2日です。税理士事務所に確認したところ、試算表は用意できているとのことですが、社長のご確認・承認が必要とのことです。',
    sentAt: '2026-06-27T11:00:00+09:00',
    category: 'finance',
    urgency: 'high',
    hasAttachment: false,
    isRead: false,
    readOnly: true,
    writeEnabled: false,
    requiresApproval: true,
    priority: 'A',
    subject: '△△銀行融資審査：試算表確認・承認依頼',
    bodyPreview: '△△銀行融資審査用の試算表確認・承認依頼。提出期限：7月2日。税理士事務所より確認済み。',
    deadline: '2026-07-02',
    suggestedAction: '試算表の内容確認と税理士事務所への承認連絡',
  },
]
