import type {
  UnifiedBusinessMetric,
  UnifiedCashflowWeek,
  UnifiedProjectProfit,
  UnifiedDepartmentMetric,
  UnifiedBusinessDataset,
} from '../../core/providers/providerTypes'

const NOW = '2026-06-27T09:00:00+09:00'

export const mockMetrics: UnifiedBusinessMetric[] = [
  {
    id: 'metric-revenue-jun',
    source: 'デモSheets',
    providerType: 'business-data',
    metricKey: 'monthly_revenue',
    metricName: '今月売上',
    category: '売上',
    value: 28400000,
    unit: '円',
    period: '2026-06',
    previousValue: 25200000,
    changeAmount: 3200000,
    changeRate: 12.7,
    status: 'normal',
    riskLevel: null,
    relatedCompany: null,
    relatedDepartment: null,
    relatedProject: null,
    suggestedAction: null,
    dataSourceName: 'デモSheets・売上管理',
    lastUpdatedAt: NOW,
    alertLevel: 'info',
    alertReason: null,
    label: '今月売上',
    trend: 'up',
    readOnly: true,
    writeEnabled: false,
  },
  {
    id: 'metric-gross-profit-jun',
    source: 'デモSheets',
    providerType: 'business-data',
    metricKey: 'monthly_gross_profit',
    metricName: '今月粗利',
    category: '粗利',
    value: 8100000,
    unit: '円',
    period: '2026-06',
    previousValue: 7800000,
    changeAmount: 300000,
    changeRate: 3.8,
    status: 'normal',
    riskLevel: null,
    relatedCompany: null,
    relatedDepartment: null,
    relatedProject: null,
    suggestedAction: null,
    dataSourceName: 'デモSheets・売上管理',
    lastUpdatedAt: NOW,
    alertLevel: 'info',
    alertReason: null,
    label: '今月粗利',
    trend: 'up',
    readOnly: true,
    writeEnabled: false,
  },
  {
    id: 'metric-gross-profit-rate',
    source: 'デモSheets',
    providerType: 'business-data',
    metricKey: 'gross_profit_rate',
    metricName: '今月粗利率',
    category: '粗利',
    value: 28.5,
    unit: '%',
    period: '2026-06',
    previousValue: 30.9,
    changeAmount: -2.4,
    changeRate: -7.8,
    status: 'warning',
    riskLevel: 'medium',
    relatedCompany: null,
    relatedDepartment: null,
    relatedProject: null,
    suggestedAction: '外注費比率を確認してください',
    dataSourceName: 'デモSheets・売上管理',
    lastUpdatedAt: NOW,
    alertLevel: 'warning',
    alertReason: '前月比 -2.4pt。目標30%を下回っています',
    label: '今月粗利率',
    trend: 'down',
    readOnly: true,
    writeEnabled: false,
  },
  {
    id: 'metric-cash-balance',
    source: 'デモSheets',
    providerType: 'business-data',
    metricKey: 'cash_balance',
    metricName: '現金残高',
    category: '資金繰り',
    value: 4200000,
    unit: '円',
    period: '2026-06-27',
    previousValue: 5800000,
    changeAmount: -1600000,
    changeRate: -27.6,
    status: 'warning',
    riskLevel: 'high',
    relatedCompany: null,
    relatedDepartment: null,
    relatedProject: null,
    suggestedAction: '資金繰り表を確認し、入金予定を銀行へ報告してください',
    dataSourceName: 'デモSheets・資金繰り',
    lastUpdatedAt: NOW,
    alertLevel: 'warning',
    alertReason: '残高が前月比 -27.6%。銀行との打合せが本日あります',
    label: '現金残高',
    trend: 'down',
    readOnly: true,
    writeEnabled: false,
  },
  {
    id: 'metric-unbilled',
    source: 'デモSheets',
    providerType: 'business-data',
    metricKey: 'unbilled',
    metricName: '未請求',
    category: '請求',
    value: 6800000,
    unit: '円',
    period: '2026-06',
    previousValue: 5100000,
    changeAmount: 1700000,
    changeRate: 33.3,
    status: 'danger',
    riskLevel: 'high',
    relatedCompany: 'お結び株式会社',
    relatedDepartment: null,
    relatedProject: null,
    suggestedAction: '未請求一覧を確認し、請求書発行を急いでください',
    dataSourceName: 'デモSheets・請求管理',
    lastUpdatedAt: NOW,
    alertLevel: 'danger',
    alertReason: '未請求額が前月比 +33%。「未請求一覧_6月.xlsx」参照',
    label: '未請求',
    trend: 'up',
    readOnly: true,
    writeEnabled: false,
  },
  {
    id: 'metric-uncollected',
    source: 'デモSheets',
    providerType: 'business-data',
    metricKey: 'uncollected',
    metricName: '未回収',
    category: '未回収',
    value: 3200000,
    unit: '円',
    period: '2026-06',
    previousValue: 2400000,
    changeAmount: 800000,
    changeRate: 33.3,
    status: 'warning',
    riskLevel: 'medium',
    relatedCompany: null,
    relatedDepartment: null,
    relatedProject: null,
    suggestedAction: '未回収先への督促を検討してください',
    dataSourceName: 'デモSheets・売掛管理',
    lastUpdatedAt: NOW,
    alertLevel: 'warning',
    alertReason: '未回収額が前月比 +33%',
    label: '未回収',
    trend: 'up',
    readOnly: true,
    writeEnabled: false,
  },
  {
    id: 'metric-accident',
    source: 'デモSheets',
    providerType: 'business-data',
    metricKey: 'accident_count',
    metricName: '事故件数（今月）',
    category: '事故',
    value: 1,
    unit: '件',
    period: '2026-06',
    previousValue: 0,
    changeAmount: 1,
    changeRate: null,
    status: 'danger',
    riskLevel: 'critical',
    relatedCompany: null,
    relatedDepartment: '現場部門',
    relatedProject: null,
    suggestedAction: '事故報告書を確認し、再発防止策を策定してください',
    dataSourceName: 'デモSheets・安全管理',
    lastUpdatedAt: NOW,
    alertLevel: 'danger',
    alertReason: '今月1件の事故が発生しています。「車両事故報告書.pdf」参照',
    label: '事故件数（今月）',
    trend: 'up',
    readOnly: true,
    writeEnabled: false,
  },
  {
    id: 'metric-utilization',
    source: 'デモSheets',
    providerType: 'business-data',
    metricKey: 'utilization_rate',
    metricName: '社員稼働率',
    category: '稼働率',
    value: 87,
    unit: '%',
    period: '2026-06',
    previousValue: 91,
    changeAmount: -4,
    changeRate: -4.4,
    status: 'warning',
    riskLevel: 'low',
    relatedCompany: null,
    relatedDepartment: null,
    relatedProject: null,
    suggestedAction: '稼働率低下の原因を確認してください',
    dataSourceName: 'デモSheets・人事管理',
    lastUpdatedAt: NOW,
    alertLevel: 'warning',
    alertReason: '前月比 -4pt。目標90%を下回っています',
    label: '社員稼働率',
    trend: 'down',
    readOnly: true,
    writeEnabled: false,
  },
]

export const mockCashflowWeeks: UnifiedCashflowWeek[] = [
  { week: '6/30', income: 280, expense: 320, balance: 420, alert: false, alertLevel: null },
  { week: '7/7', income: 150, expense: 200, balance: 370, alert: true, alertLevel: 'warning' },
  { week: '7/14', income: 420, expense: 180, balance: 610, alert: false, alertLevel: null },
  { week: '7/21', income: 90, expense: 280, balance: 420, alert: true, alertLevel: 'warning' },
  { week: '7/28', income: 380, expense: 220, balance: 580, alert: false, alertLevel: null },
  { week: '8/4', income: 200, expense: 310, balance: 470, alert: false, alertLevel: null },
  { week: '8/11', income: 50, expense: 290, balance: 230, alert: true, alertLevel: 'danger' },
  { week: '8/18', income: 520, expense: 190, balance: 560, alert: false, alertLevel: null },
  { week: '8/25', income: 180, expense: 250, balance: 490, alert: false, alertLevel: null },
  { week: '9/1', income: 310, expense: 200, balance: 600, alert: false, alertLevel: null },
  { week: '9/8', income: 140, expense: 280, balance: 460, alert: false, alertLevel: null },
  { week: '9/15', income: 400, expense: 210, balance: 650, alert: false, alertLevel: null },
  { week: '9/22', income: 230, expense: 190, balance: 690, alert: false, alertLevel: null },
]

export const mockProjectProfits: UnifiedProjectProfit[] = [
  { id: 'proj-1', projectName: '〇〇邸 新築工事', revenue: 8500000, grossProfit: 2800000, grossProfitRate: 32.9, relatedCompany: '〇〇建設', relatedDepartment: '現場部門', alert: false },
  { id: 'proj-2', projectName: 'お結び 介護サービス', revenue: 6200000, grossProfit: 2170000, grossProfitRate: 35.0, relatedCompany: 'お結び株式会社', relatedDepartment: '福祉部門', alert: false },
  { id: 'proj-3', projectName: '△△社 保守契約', revenue: 4800000, grossProfit: 1056000, grossProfitRate: 22.0, relatedCompany: '△△株式会社', relatedDepartment: '営業部門', alert: true },
  { id: 'proj-4', projectName: '〇〇市 委託業務', revenue: 5100000, grossProfit: 1530000, grossProfitRate: 30.0, relatedCompany: '〇〇市', relatedDepartment: '事務部門', alert: false },
  { id: 'proj-5', projectName: '✕✕社 スポット対応', revenue: 3800000, grossProfit: 646000, grossProfitRate: 17.0, relatedCompany: '✕✕株式会社', relatedDepartment: '現場部門', alert: true },
]

export const mockDepartmentMetrics: UnifiedDepartmentMetric[] = [
  { id: 'dept-1', departmentName: '現場部門', revenue: 14200000, profit: 4545000, profitRate: 32, headcount: 8 },
  { id: 'dept-2', departmentName: '福祉部門', revenue: 8900000, profit: 2847000, profitRate: 32, headcount: 5 },
  { id: 'dept-3', departmentName: '営業部門', revenue: 6800000, profit: 1360000, profitRate: 20, headcount: 3 },
  { id: 'dept-4', departmentName: '事務部門', revenue: 5100000, profit: 1530000, profitRate: 30, headcount: 4 },
]

export const mockBusinessDataset: UnifiedBusinessDataset = {
  metrics: mockMetrics,
  cashflowWeeks: mockCashflowWeeks,
  projectProfits: mockProjectProfits,
  departmentMetrics: mockDepartmentMetrics,
  source: 'mock',
  fetchedAt: NOW,
}
